
#配置服务端口
#配置服务名
#配置eureka注册地址
server:
  port: 9091
spring:
  application:
    name: producer-service2
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8762/eureka, http://root:root@localhost:8761/eureka



