server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:8762/eureka/
# 指定用户名和密码
spring:
  security:
    user:
      name: root
      password: root




