server:
  port: 10004
spring:
  application:
    name: consumer2-ribbon
eureka:
  client:
    service-url:
      defaultZone:  http://root:root@localhost:8762/eureka, http://root:root@localhost:8761/eureka
# 指定具体服务的负载均衡策略
#producer-service2:      # 编写服务名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule  # 具体负载均衡使用的类


